# As of August 26, 2026, Actionlint via Super-Linter does not support Ubuntu
# 26.04, so we ignore this runner-label warning for now.
paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      - 'label "ubuntu-26.04" is unknown.+'
