version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(ci)"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore"
      include: "scope"
