---
name: Build and Test Wheels

on:
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    permissions:
      contents: read
      packages: read
      id-token: write
    uses: ./.github/workflows/wheels.yml
