---
name: Build and Upload Wheels to PyPI

on:
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    if: github.ref_type == 'tag'
    permissions:
      contents: read
      packages: read
      id-token: write
    uses: ./.github/workflows/wheels.yml
    with:
      pypi-repository: "pypi"
      pypi-url: "https://pypi.org/p/mmh3"
      pypi-endpoint: "https://upload.pypi.org/legacy/"
