---
name: Build and Upload Wheels to TestPyPI

on:
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/wheels.yml
    with:
      pypi-repository: "testpypi"
      pypi-url: "https://test.pypi.org/p/mmh3"
      pypi-endpoint: https://test.pypi.org/legacy/
